title: Singapore Customs
url: "" # the base hostname & protocol for your site, e.g. http://example.com
favicon: /images/favicon.png

# Site colors
colors:
  primary-color: '#041D42'
  secondary-color: '#041D42'
  media-colors:
    - title: media-color-one
      color: '#A2AAAD'
    - title: media-color-two
      color: '#20639B'
    - title: media-color-three
      color: '#990000'
    - title: media-color-four
      color: '#F5C936'
    - title: media-color-five
      color: '#041D42'

resources_name: news-and-media

collections:
  about-us:
    output: true
  organisation-overview:
    output: true
  individuals:
    output: true
  businesses:
    output: true
  news-and-media:
    output: true
  eservices:
    output: true
  individuals_going-through-customs:
    output: true
  registration-procedures:
    output: true
  business_hidden_business-resources:
   output: true
  importing-goods-more: 
    output: true
  business_hidden_transhipment-procedures: 
    output: true
  business_hidden_transhipment-procedures-requirements:
    output: true
  business_hidden_chemical-weapons-convention: 
    output: true
  business_hidden_CWC-inspections: 
    output: true
  business_hidden_CWC-licensing-requirements: 
    output: true
  business_hidden_strategic-goods-permit-and-reg-req: 
    output: true
  business_hidden_strategic-goods-control: 
    output: true
  business_hidden_iras-scheme: 
    output: true
  business_hidden_establishing-customs-value-for-imports: 
    output: true
  business_hidden_import-procedures-req: 
    output: true
  importing-by-post-or-courier-service:
    output: true
  business_hidden_temporary-import-scheme:
    output: true
  importing-dutiable-motor-vehicles:
    output: true
  business_hidden_importing-dutiable-motor-vehicles-steps:
    output: true
  importing-goods-for-destruction-or-recycling:
    output: true
  business_hidden_export-procedures-requirements:
    output: true
  business_hidden_authorised-piers-places: 
    output: true
  business_hidden_united-nations-security-council-sanctions: 
    output: true
  business_hidden_strategic-goods-control-list:
    output: true
  business_hidden_import-certificate-and-delivery-verification:
    output: true
  test_hidden:
    output: true
  business_hidden_tradenet:
    output: true 
  business_hidden_export-procedures-more:
    output: true   
  business_hidden_registration-security-lodgement:
    output: true    
  business_hidden_apply-update-renew-terminate-declarant-agent:
    output: true   
  business_hidden_import-permit-req-IPMs:   
    output: true   
  business_hidden_competent-authorities-requirements:   
    output: true  
  competent-authorities-requirements:   
    output: true          
##################################################################################################################
# Everything below this line is Isomer-specific configuration. There should not be a need to edit these settings #
##################################################################################################################
permalink: none
baseurl: ""
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
include: [_redirects]
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
description: test test

